// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/freezeData.dart';
import 'models/memberAttendencesData.dart';
import 'models/memberData.dart';
import 'models/planData.dart';
import 'models/registrations.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6056883884754354610),
      name: 'MemberAttendencesData',
      lastPropertyId: const IdUid(10, 2596117925268838224),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8169497247661579549),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2345819803651470036),
            name: 'attendenceId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(1, 1159075281728089432)),
        ModelProperty(
            id: const IdUid(3, 8188357564399082483),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7066691399028144783),
            name: 'registrationId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3395273663782249141),
            name: 'packageId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 8869910621790644374),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6431169059026718264),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 4255425999697188401),
            name: 'createdAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 1246980052512881873),
            name: 'sync',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2596117925268838224),
            name: 'operation',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 1378476243543860403),
      name: 'MemberData',
      lastPropertyId: const IdUid(18, 4367868579330038011),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1327096607227096529),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2346699890881089942),
            name: 'memberId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(2, 1837140264222339056)),
        ModelProperty(
            id: const IdUid(3, 3151209096687426663),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4104382264962712542),
            name: 'memberName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2734083810871850484),
            name: 'memberEmail',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1637269263225563133),
            name: 'memberPhone',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1390623700632304518),
            name: 'countryCode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8766273012310475773),
            name: 'gender',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 2283240956786735449),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 5909434463870896822),
            name: 'birthYear',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 2700222471103630308),
            name: 'membership',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 4066257226581993699),
            name: 'qrCodeURL',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 4476010865810478439),
            name: 'qrCodeUUID',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 7297387878379818925),
            name: 'canAuthenticate',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 8121602908880867042),
            name: 'isBlocked',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 1699879179378669295),
            name: 'createdAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 2525735113657400380),
            name: 'sync',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(18, 4367868579330038011),
            name: 'operation',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 6117331727512201037),
      name: 'PlanData',
      lastPropertyId: const IdUid(9, 9218704704895438055),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2055748579743814447),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3153108036962973229),
            name: 'planId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(3, 3634938526974646890)),
        ModelProperty(
            id: const IdUid(3, 4155091816015290920),
            name: 'planClubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 9130022310736290158),
            name: 'planTitle',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2971009903352727492),
            name: 'planAttendance',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 9187614272923877199),
            name: 'planExpiresIn',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6444831550383976250),
            name: 'planPriceAsDouble',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 4580966611257982922),
            name: 'isOpen',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 9218704704895438055),
            name: 'createdAt',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 3406677903734350214),
      name: 'Registrations',
      lastPropertyId: const IdUid(14, 5664607878573124509),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4520363289792743168),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3053439158363842617),
            name: 'registrationId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(4, 428676365675191002)),
        ModelProperty(
            id: const IdUid(3, 8078348712793049997),
            name: 'registrationIsActive',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8775719121391207079),
            name: 'registrationAttended',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1821000588783123408),
            name: 'registrationExpiresAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3473648902154709816),
            name: 'isFreezed',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4180076389178885717),
            name: 'registrationCreatedAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7549396928965287341),
            name: 'packageId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3133062373805329446),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 9039426038273245385),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 97440965990419427),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 1225971394730537049),
            name: 'paidInDouble',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 7766414752817843838),
            name: 'sync',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 5664607878573124509),
            name: 'operation',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 5749498089857437392),
      name: 'FreezeData',
      lastPropertyId: const IdUid(12, 2441504589874321887),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1229900531739855747),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2559956367324272576),
            name: 'freezeId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(5, 7049012826544978838)),
        ModelProperty(
            id: const IdUid(3, 7598401897659363695),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7398454180954510446),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4730986890483889962),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4746919108582063692),
            name: 'registrationId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 964660946994162657),
            name: 'packageId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5655410925035416110),
            name: 'reactivationDate',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 2997959157087849375),
            name: 'freezeDuration',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 4609835529531803954),
            name: 'registrationNewExpirationDate',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 3887069025824403465),
            name: 'sync',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 2441504589874321887),
            name: 'operation',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String directory,
        int maxDBSizeInKB,
        int fileMode,
        int maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(5, 5749498089857437392),
      lastIndexId: const IdUid(5, 7049012826544978838),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MemberAttendencesData: EntityDefinition<MemberAttendencesData>(
        model: _entities[0],
        toOneRelations: (MemberAttendencesData object) => [],
        toManyRelations: (MemberAttendencesData object) => {},
        getId: (MemberAttendencesData object) => object.id,
        setId: (MemberAttendencesData object, int id) {
          object.id = id;
        },
        objectToFB: (MemberAttendencesData object, fb.Builder fbb) {
          final attendenceIdOffset = object.attendenceId == null
              ? null
              : fbb.writeString(object.attendenceId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final registrationIdOffset = object.registrationId == null
              ? null
              : fbb.writeString(object.registrationId);
          final packageIdOffset = object.packageId == null
              ? null
              : fbb.writeString(object.packageId);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          final operationOffset = object.operation == null
              ? null
              : fbb.writeString(object.operation);
          fbb.startTable(11);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, attendenceIdOffset);
          fbb.addOffset(2, clubIdOffset);
          fbb.addOffset(3, registrationIdOffset);
          fbb.addOffset(4, packageIdOffset);
          fbb.addOffset(5, staffIdOffset);
          fbb.addOffset(6, memberIdOffset);
          fbb.addOffset(7, createdAtOffset);
          fbb.addBool(8, object.sync);
          fbb.addOffset(9, operationOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MemberAttendencesData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              attendenceId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              registrationId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              packageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              staffId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              memberId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              createdAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              sync: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 20),
              operation: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22));

          return object;
        }),
    MemberData: EntityDefinition<MemberData>(
        model: _entities[1],
        toOneRelations: (MemberData object) => [],
        toManyRelations: (MemberData object) => {},
        getId: (MemberData object) => object.id,
        setId: (MemberData object, int id) {
          object.id = id;
        },
        objectToFB: (MemberData object, fb.Builder fbb) {
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final memberNameOffset = object.memberName == null
              ? null
              : fbb.writeString(object.memberName);
          final memberEmailOffset = object.memberEmail == null
              ? null
              : fbb.writeString(object.memberEmail);
          final memberPhoneOffset = object.memberPhone == null
              ? null
              : fbb.writeString(object.memberPhone);
          final countryCodeOffset = object.countryCode == null
              ? null
              : fbb.writeString(object.countryCode);
          final genderOffset =
              object.gender == null ? null : fbb.writeString(object.gender);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final birthYearOffset = object.birthYear == null
              ? null
              : fbb.writeString(object.birthYear);
          final qrCodeURLOffset = object.qrCodeURL == null
              ? null
              : fbb.writeString(object.qrCodeURL);
          final qrCodeUUIDOffset = object.qrCodeUUID == null
              ? null
              : fbb.writeString(object.qrCodeUUID);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          final operationOffset = object.operation == null
              ? null
              : fbb.writeString(object.operation);
          fbb.startTable(19);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, memberIdOffset);
          fbb.addOffset(2, clubIdOffset);
          fbb.addOffset(3, memberNameOffset);
          fbb.addOffset(4, memberEmailOffset);
          fbb.addOffset(5, memberPhoneOffset);
          fbb.addOffset(6, countryCodeOffset);
          fbb.addOffset(7, genderOffset);
          fbb.addOffset(8, staffIdOffset);
          fbb.addOffset(9, birthYearOffset);
          fbb.addInt64(10, object.membership);
          fbb.addOffset(11, qrCodeURLOffset);
          fbb.addOffset(12, qrCodeUUIDOffset);
          fbb.addBool(13, object.canAuthenticate);
          fbb.addBool(14, object.isBlocked);
          fbb.addOffset(15, createdAtOffset);
          fbb.addBool(16, object.sync);
          fbb.addOffset(17, operationOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MemberData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              countryCode: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              memberEmail: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              membership: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 24),
              qrCodeURL: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26),
              qrCodeUUID: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28),
              staffId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              gender: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 18),
              birthYear: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              isBlocked: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 32),
              createdAt: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 34),
              canAuthenticate: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 30),
              memberId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 6),
              memberName: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10),
              memberPhone: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 14),
              sync: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 36),
              operation: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 38));

          return object;
        }),
    PlanData: EntityDefinition<PlanData>(
        model: _entities[2],
        toOneRelations: (PlanData object) => [],
        toManyRelations: (PlanData object) => {},
        getId: (PlanData object) => object.id,
        setId: (PlanData object, int id) {
          object.id = id;
        },
        objectToFB: (PlanData object, fb.Builder fbb) {
          final planIdOffset =
              object.planId == null ? null : fbb.writeString(object.planId);
          final planClubIdOffset = object.planClubId == null
              ? null
              : fbb.writeString(object.planClubId);
          final planTitleOffset = object.planTitle == null
              ? null
              : fbb.writeString(object.planTitle);
          final planExpiresInOffset = object.planExpiresIn == null
              ? null
              : fbb.writeString(object.planExpiresIn);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          fbb.startTable(10);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, planIdOffset);
          fbb.addOffset(2, planClubIdOffset);
          fbb.addOffset(3, planTitleOffset);
          fbb.addInt64(4, object.planAttendance);
          fbb.addOffset(5, planExpiresInOffset);
          fbb.addFloat64(6, object.planPriceAsDouble);
          fbb.addBool(7, object.isOpen);
          fbb.addOffset(8, createdAtOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PlanData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              planId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              planClubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              planTitle: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              planAttendance: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              planExpiresIn: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              isOpen: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 18),
              createdAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              planPriceAsDouble: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 16));

          return object;
        }),
    Registrations: EntityDefinition<Registrations>(
        model: _entities[3],
        toOneRelations: (Registrations object) => [],
        toManyRelations: (Registrations object) => {},
        getId: (Registrations object) => object.id,
        setId: (Registrations object, int id) {
          object.id = id;
        },
        objectToFB: (Registrations object, fb.Builder fbb) {
          final registrationIdOffset = object.registrationId == null
              ? null
              : fbb.writeString(object.registrationId);
          final registrationExpiresAtOffset =
              object.registrationExpiresAt == null
                  ? null
                  : fbb.writeString(object.registrationExpiresAt);
          final registrationCreatedAtOffset =
              object.registrationCreatedAt == null
                  ? null
                  : fbb.writeString(object.registrationCreatedAt);
          final packageIdOffset = object.packageId == null
              ? null
              : fbb.writeString(object.packageId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final operationOffset = object.operation == null
              ? null
              : fbb.writeString(object.operation);
          fbb.startTable(15);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, registrationIdOffset);
          fbb.addBool(2, object.registrationIsActive);
          fbb.addInt64(3, object.registrationAttended);
          fbb.addOffset(4, registrationExpiresAtOffset);
          fbb.addBool(5, object.isFreezed);
          fbb.addOffset(6, registrationCreatedAtOffset);
          fbb.addOffset(7, packageIdOffset);
          fbb.addOffset(8, clubIdOffset);
          fbb.addOffset(9, memberIdOffset);
          fbb.addOffset(10, staffIdOffset);
          fbb.addFloat64(11, object.paidInDouble);
          fbb.addBool(12, object.sync);
          fbb.addOffset(13, operationOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Registrations(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              registrationId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              registrationIsActive: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              registrationAttended: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              registrationExpiresAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              isFreezed: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              registrationCreatedAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              packageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              memberId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              staffId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 24),
              paidInDouble: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 26),
              sync: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 28),
              operation: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 30));

          return object;
        }),
    FreezeData: EntityDefinition<FreezeData>(
        model: _entities[4],
        toOneRelations: (FreezeData object) => [],
        toManyRelations: (FreezeData object) => {},
        getId: (FreezeData object) => object.id,
        setId: (FreezeData object, int id) {
          object.id = id;
        },
        objectToFB: (FreezeData object, fb.Builder fbb) {
          final freezeIdOffset =
              object.freezeId == null ? null : fbb.writeString(object.freezeId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final registrationIdOffset = object.registrationId == null
              ? null
              : fbb.writeString(object.registrationId);
          final packageIdOffset = object.packageId == null
              ? null
              : fbb.writeString(object.packageId);
          final reactivationDateOffset = object.reactivationDate == null
              ? null
              : fbb.writeString(object.reactivationDate);
          final freezeDurationOffset = object.freezeDuration == null
              ? null
              : fbb.writeString(object.freezeDuration);
          final registrationNewExpirationDateOffset =
              object.registrationNewExpirationDate == null
                  ? null
                  : fbb.writeString(object.registrationNewExpirationDate);
          final operationOffset = object.operation == null
              ? null
              : fbb.writeString(object.operation);
          fbb.startTable(13);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, freezeIdOffset);
          fbb.addOffset(2, clubIdOffset);
          fbb.addOffset(3, staffIdOffset);
          fbb.addOffset(4, memberIdOffset);
          fbb.addOffset(5, registrationIdOffset);
          fbb.addOffset(6, packageIdOffset);
          fbb.addOffset(7, reactivationDateOffset);
          fbb.addOffset(8, freezeDurationOffset);
          fbb.addOffset(9, registrationNewExpirationDateOffset);
          fbb.addBool(10, object.sync);
          fbb.addOffset(11, operationOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FreezeData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              freezeId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              staffId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              memberId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              registrationId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              packageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              reactivationDate: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              freezeDuration: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 20),
              registrationNewExpirationDate: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              sync: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 24),
              operation: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 26));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MemberAttendencesData] entity fields to define ObjectBox queries.
class MemberAttendencesData_ {
  /// see [MemberAttendencesData.id]
  static final id =
      QueryIntegerProperty<MemberAttendencesData>(_entities[0].properties[0]);

  /// see [MemberAttendencesData.attendenceId]
  static final attendenceId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[1]);

  /// see [MemberAttendencesData.clubId]
  static final clubId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[2]);

  /// see [MemberAttendencesData.registrationId]
  static final registrationId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[3]);

  /// see [MemberAttendencesData.packageId]
  static final packageId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[4]);

  /// see [MemberAttendencesData.staffId]
  static final staffId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[5]);

  /// see [MemberAttendencesData.memberId]
  static final memberId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[6]);

  /// see [MemberAttendencesData.createdAt]
  static final createdAt =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[7]);

  /// see [MemberAttendencesData.sync]
  static final sync =
      QueryBooleanProperty<MemberAttendencesData>(_entities[0].properties[8]);

  /// see [MemberAttendencesData.operation]
  static final operation =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[9]);
}

/// [MemberData] entity fields to define ObjectBox queries.
class MemberData_ {
  /// see [MemberData.id]
  static final id =
      QueryIntegerProperty<MemberData>(_entities[1].properties[0]);

  /// see [MemberData.memberId]
  static final memberId =
      QueryStringProperty<MemberData>(_entities[1].properties[1]);

  /// see [MemberData.clubId]
  static final clubId =
      QueryStringProperty<MemberData>(_entities[1].properties[2]);

  /// see [MemberData.memberName]
  static final memberName =
      QueryStringProperty<MemberData>(_entities[1].properties[3]);

  /// see [MemberData.memberEmail]
  static final memberEmail =
      QueryStringProperty<MemberData>(_entities[1].properties[4]);

  /// see [MemberData.memberPhone]
  static final memberPhone =
      QueryStringProperty<MemberData>(_entities[1].properties[5]);

  /// see [MemberData.countryCode]
  static final countryCode =
      QueryStringProperty<MemberData>(_entities[1].properties[6]);

  /// see [MemberData.gender]
  static final gender =
      QueryStringProperty<MemberData>(_entities[1].properties[7]);

  /// see [MemberData.staffId]
  static final staffId =
      QueryStringProperty<MemberData>(_entities[1].properties[8]);

  /// see [MemberData.birthYear]
  static final birthYear =
      QueryStringProperty<MemberData>(_entities[1].properties[9]);

  /// see [MemberData.membership]
  static final membership =
      QueryIntegerProperty<MemberData>(_entities[1].properties[10]);

  /// see [MemberData.qrCodeURL]
  static final qrCodeURL =
      QueryStringProperty<MemberData>(_entities[1].properties[11]);

  /// see [MemberData.qrCodeUUID]
  static final qrCodeUUID =
      QueryStringProperty<MemberData>(_entities[1].properties[12]);

  /// see [MemberData.canAuthenticate]
  static final canAuthenticate =
      QueryBooleanProperty<MemberData>(_entities[1].properties[13]);

  /// see [MemberData.isBlocked]
  static final isBlocked =
      QueryBooleanProperty<MemberData>(_entities[1].properties[14]);

  /// see [MemberData.createdAt]
  static final createdAt =
      QueryStringProperty<MemberData>(_entities[1].properties[15]);

  /// see [MemberData.sync]
  static final sync =
      QueryBooleanProperty<MemberData>(_entities[1].properties[16]);

  /// see [MemberData.operation]
  static final operation =
      QueryStringProperty<MemberData>(_entities[1].properties[17]);
}

/// [PlanData] entity fields to define ObjectBox queries.
class PlanData_ {
  /// see [PlanData.id]
  static final id = QueryIntegerProperty<PlanData>(_entities[2].properties[0]);

  /// see [PlanData.planId]
  static final planId =
      QueryStringProperty<PlanData>(_entities[2].properties[1]);

  /// see [PlanData.planClubId]
  static final planClubId =
      QueryStringProperty<PlanData>(_entities[2].properties[2]);

  /// see [PlanData.planTitle]
  static final planTitle =
      QueryStringProperty<PlanData>(_entities[2].properties[3]);

  /// see [PlanData.planAttendance]
  static final planAttendance =
      QueryIntegerProperty<PlanData>(_entities[2].properties[4]);

  /// see [PlanData.planExpiresIn]
  static final planExpiresIn =
      QueryStringProperty<PlanData>(_entities[2].properties[5]);

  /// see [PlanData.planPriceAsDouble]
  static final planPriceAsDouble =
      QueryDoubleProperty<PlanData>(_entities[2].properties[6]);

  /// see [PlanData.isOpen]
  static final isOpen =
      QueryBooleanProperty<PlanData>(_entities[2].properties[7]);

  /// see [PlanData.createdAt]
  static final createdAt =
      QueryStringProperty<PlanData>(_entities[2].properties[8]);
}

/// [Registrations] entity fields to define ObjectBox queries.
class Registrations_ {
  /// see [Registrations.id]
  static final id =
      QueryIntegerProperty<Registrations>(_entities[3].properties[0]);

  /// see [Registrations.registrationId]
  static final registrationId =
      QueryStringProperty<Registrations>(_entities[3].properties[1]);

  /// see [Registrations.registrationIsActive]
  static final registrationIsActive =
      QueryBooleanProperty<Registrations>(_entities[3].properties[2]);

  /// see [Registrations.registrationAttended]
  static final registrationAttended =
      QueryIntegerProperty<Registrations>(_entities[3].properties[3]);

  /// see [Registrations.registrationExpiresAt]
  static final registrationExpiresAt =
      QueryStringProperty<Registrations>(_entities[3].properties[4]);

  /// see [Registrations.isFreezed]
  static final isFreezed =
      QueryBooleanProperty<Registrations>(_entities[3].properties[5]);

  /// see [Registrations.registrationCreatedAt]
  static final registrationCreatedAt =
      QueryStringProperty<Registrations>(_entities[3].properties[6]);

  /// see [Registrations.packageId]
  static final packageId =
      QueryStringProperty<Registrations>(_entities[3].properties[7]);

  /// see [Registrations.clubId]
  static final clubId =
      QueryStringProperty<Registrations>(_entities[3].properties[8]);

  /// see [Registrations.memberId]
  static final memberId =
      QueryStringProperty<Registrations>(_entities[3].properties[9]);

  /// see [Registrations.staffId]
  static final staffId =
      QueryStringProperty<Registrations>(_entities[3].properties[10]);

  /// see [Registrations.paidInDouble]
  static final paidInDouble =
      QueryDoubleProperty<Registrations>(_entities[3].properties[11]);

  /// see [Registrations.sync]
  static final sync =
      QueryBooleanProperty<Registrations>(_entities[3].properties[12]);

  /// see [Registrations.operation]
  static final operation =
      QueryStringProperty<Registrations>(_entities[3].properties[13]);
}

/// [FreezeData] entity fields to define ObjectBox queries.
class FreezeData_ {
  /// see [FreezeData.id]
  static final id =
      QueryIntegerProperty<FreezeData>(_entities[4].properties[0]);

  /// see [FreezeData.freezeId]
  static final freezeId =
      QueryStringProperty<FreezeData>(_entities[4].properties[1]);

  /// see [FreezeData.clubId]
  static final clubId =
      QueryStringProperty<FreezeData>(_entities[4].properties[2]);

  /// see [FreezeData.staffId]
  static final staffId =
      QueryStringProperty<FreezeData>(_entities[4].properties[3]);

  /// see [FreezeData.memberId]
  static final memberId =
      QueryStringProperty<FreezeData>(_entities[4].properties[4]);

  /// see [FreezeData.registrationId]
  static final registrationId =
      QueryStringProperty<FreezeData>(_entities[4].properties[5]);

  /// see [FreezeData.packageId]
  static final packageId =
      QueryStringProperty<FreezeData>(_entities[4].properties[6]);

  /// see [FreezeData.reactivationDate]
  static final reactivationDate =
      QueryStringProperty<FreezeData>(_entities[4].properties[7]);

  /// see [FreezeData.freezeDuration]
  static final freezeDuration =
      QueryStringProperty<FreezeData>(_entities[4].properties[8]);

  /// see [FreezeData.registrationNewExpirationDate]
  static final registrationNewExpirationDate =
      QueryStringProperty<FreezeData>(_entities[4].properties[9]);

  /// see [FreezeData.sync]
  static final sync =
      QueryBooleanProperty<FreezeData>(_entities[4].properties[10]);

  /// see [FreezeData.operation]
  static final operation =
      QueryStringProperty<FreezeData>(_entities[4].properties[11]);
}
