// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/memberAttendencesData.dart';
import 'models/memberData.dart';
import 'models/planData.dart';
import 'models/registrations.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3277042433751473766),
      name: 'MemberAttendencesData',
      lastPropertyId: const IdUid(8, 8095750558975633293),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5241358954501170570),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8081275980363410646),
            name: 'attendenceId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2170278292602645620),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 690378031368188195),
            name: 'registrationId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2960132676514182521),
            name: 'packageId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 32578052699882140),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4024953480403865323),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8095750558975633293),
            name: 'createdAt',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 2641695348687829254),
      name: 'MemberData',
      lastPropertyId: const IdUid(16, 6915709157516983869),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5213011548525722191),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 446653268271102516),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4952610577579292300),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8116882161731740592),
            name: 'memberName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 2472172255173004662),
            name: 'memberEmail',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1480325873941322594),
            name: 'memberPhone',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5829525266723065547),
            name: 'countryCode',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 5572854357120317637),
            name: 'gender',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 4711096227790351391),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 8196664111727738928),
            name: 'birthYear',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 5076980551054798833),
            name: 'membership',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 4272734845516564511),
            name: 'qrCodeURL',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 4959229988983520679),
            name: 'qrCodeUUID',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 2252141030897888578),
            name: 'canAuthenticate',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 3527483509806615196),
            name: 'isBlocked',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 6915709157516983869),
            name: 'createdAt',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 5711936982490007564),
      name: 'PlanData',
      lastPropertyId: const IdUid(8, 7063943295511765215),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2655322610188363126),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8265917416193382037),
            name: 'planId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4384840347902940318),
            name: 'planClubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5310527877366672740),
            name: 'planTitle',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1406548675491910579),
            name: 'planAttendance',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5025555750089286984),
            name: 'planExpiresIn',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4294353273151218611),
            name: 'isOpen',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7063943295511765215),
            name: 'createdAt',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 1040338965514404000),
      name: 'Registrations',
      lastPropertyId: const IdUid(12, 2940793645541748062),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5569167664572967232),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4201647279212793466),
            name: 'registrationId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5599525302081520192),
            name: 'registrationIsActive',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8836535446117826198),
            name: 'registrationAttended',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 395470171141682650),
            name: 'registrationExpiresAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4464336874030855499),
            name: 'isFreezed',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1235500044274110141),
            name: 'registrationCreatedAt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8895855036754817901),
            name: 'packageId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7935760887756393771),
            name: 'clubId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 7526532944977469539),
            name: 'memberId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 1045110132868236767),
            name: 'staffId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 2940793645541748062),
            name: 'paid',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String directory,
        int maxDBSizeInKB,
        int fileMode,
        int maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 1040338965514404000),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    MemberAttendencesData: EntityDefinition<MemberAttendencesData>(
        model: _entities[0],
        toOneRelations: (MemberAttendencesData object) => [],
        toManyRelations: (MemberAttendencesData object) => {},
        getId: (MemberAttendencesData object) => object.id,
        setId: (MemberAttendencesData object, int id) {
          object.id = id;
        },
        objectToFB: (MemberAttendencesData object, fb.Builder fbb) {
          final attendenceIdOffset = object.attendenceId == null
              ? null
              : fbb.writeString(object.attendenceId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final registrationIdOffset = object.registrationId == null
              ? null
              : fbb.writeString(object.registrationId);
          final packageIdOffset = object.packageId == null
              ? null
              : fbb.writeString(object.packageId);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          fbb.startTable(9);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, attendenceIdOffset);
          fbb.addOffset(2, clubIdOffset);
          fbb.addOffset(3, registrationIdOffset);
          fbb.addOffset(4, packageIdOffset);
          fbb.addOffset(5, staffIdOffset);
          fbb.addOffset(6, memberIdOffset);
          fbb.addOffset(7, createdAtOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MemberAttendencesData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              attendenceId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              registrationId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              packageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              staffId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              memberId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              createdAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18));

          return object;
        }),
    MemberData: EntityDefinition<MemberData>(
        model: _entities[1],
        toOneRelations: (MemberData object) => [],
        toManyRelations: (MemberData object) => {},
        getId: (MemberData object) => object.id,
        setId: (MemberData object, int id) {
          object.id = id;
        },
        objectToFB: (MemberData object, fb.Builder fbb) {
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final memberNameOffset = object.memberName == null
              ? null
              : fbb.writeString(object.memberName);
          final memberEmailOffset = object.memberEmail == null
              ? null
              : fbb.writeString(object.memberEmail);
          final memberPhoneOffset = object.memberPhone == null
              ? null
              : fbb.writeString(object.memberPhone);
          final countryCodeOffset = object.countryCode == null
              ? null
              : fbb.writeString(object.countryCode);
          final genderOffset =
              object.gender == null ? null : fbb.writeString(object.gender);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          final birthYearOffset = object.birthYear == null
              ? null
              : fbb.writeString(object.birthYear);
          final qrCodeURLOffset = object.qrCodeURL == null
              ? null
              : fbb.writeString(object.qrCodeURL);
          final qrCodeUUIDOffset = object.qrCodeUUID == null
              ? null
              : fbb.writeString(object.qrCodeUUID);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          fbb.startTable(17);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, memberIdOffset);
          fbb.addOffset(2, clubIdOffset);
          fbb.addOffset(3, memberNameOffset);
          fbb.addOffset(4, memberEmailOffset);
          fbb.addOffset(5, memberPhoneOffset);
          fbb.addOffset(6, countryCodeOffset);
          fbb.addOffset(7, genderOffset);
          fbb.addOffset(8, staffIdOffset);
          fbb.addOffset(9, birthYearOffset);
          fbb.addInt64(10, object.membership);
          fbb.addOffset(11, qrCodeURLOffset);
          fbb.addOffset(12, qrCodeUUIDOffset);
          fbb.addBool(13, object.canAuthenticate);
          fbb.addBool(14, object.isBlocked);
          fbb.addOffset(15, createdAtOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MemberData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              countryCode: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              memberEmail: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              membership: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 24),
              qrCodeURL: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26),
              qrCodeUUID: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28),
              staffId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              gender: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 18),
              birthYear: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              isBlocked: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 32),
              createdAt: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 34),
              canAuthenticate: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 30),
              memberId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 6),
              memberName: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10),
              memberPhone: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 14));

          return object;
        }),
    PlanData: EntityDefinition<PlanData>(
        model: _entities[2],
        toOneRelations: (PlanData object) => [],
        toManyRelations: (PlanData object) => {},
        getId: (PlanData object) => object.id,
        setId: (PlanData object, int id) {
          object.id = id;
        },
        objectToFB: (PlanData object, fb.Builder fbb) {
          final planIdOffset =
              object.planId == null ? null : fbb.writeString(object.planId);
          final planClubIdOffset = object.planClubId == null
              ? null
              : fbb.writeString(object.planClubId);
          final planTitleOffset = object.planTitle == null
              ? null
              : fbb.writeString(object.planTitle);
          final planExpiresInOffset = object.planExpiresIn == null
              ? null
              : fbb.writeString(object.planExpiresIn);
          final createdAtOffset = object.createdAt == null
              ? null
              : fbb.writeString(object.createdAt);
          fbb.startTable(9);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, planIdOffset);
          fbb.addOffset(2, planClubIdOffset);
          fbb.addOffset(3, planTitleOffset);
          fbb.addInt64(4, object.planAttendance);
          fbb.addOffset(5, planExpiresInOffset);
          fbb.addBool(6, object.isOpen);
          fbb.addOffset(7, createdAtOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PlanData(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              planId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              planClubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              planTitle: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              planAttendance: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              planExpiresIn: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14),
              isOpen: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 16),
              createdAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18));

          return object;
        }),
    Registrations: EntityDefinition<Registrations>(
        model: _entities[3],
        toOneRelations: (Registrations object) => [],
        toManyRelations: (Registrations object) => {},
        getId: (Registrations object) => object.id,
        setId: (Registrations object, int id) {
          object.id = id;
        },
        objectToFB: (Registrations object, fb.Builder fbb) {
          final registrationIdOffset = object.registrationId == null
              ? null
              : fbb.writeString(object.registrationId);
          final registrationExpiresAtOffset =
              object.registrationExpiresAt == null
                  ? null
                  : fbb.writeString(object.registrationExpiresAt);
          final registrationCreatedAtOffset =
              object.registrationCreatedAt == null
                  ? null
                  : fbb.writeString(object.registrationCreatedAt);
          final packageIdOffset = object.packageId == null
              ? null
              : fbb.writeString(object.packageId);
          final clubIdOffset =
              object.clubId == null ? null : fbb.writeString(object.clubId);
          final memberIdOffset =
              object.memberId == null ? null : fbb.writeString(object.memberId);
          final staffIdOffset =
              object.staffId == null ? null : fbb.writeString(object.staffId);
          fbb.startTable(13);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, registrationIdOffset);
          fbb.addBool(2, object.registrationIsActive);
          fbb.addInt64(3, object.registrationAttended);
          fbb.addOffset(4, registrationExpiresAtOffset);
          fbb.addBool(5, object.isFreezed);
          fbb.addOffset(6, registrationCreatedAtOffset);
          fbb.addOffset(7, packageIdOffset);
          fbb.addOffset(8, clubIdOffset);
          fbb.addOffset(9, memberIdOffset);
          fbb.addOffset(10, staffIdOffset);
          fbb.addInt64(11, object.paid);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Registrations(
              id: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 4),
              registrationId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              registrationIsActive: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              registrationAttended: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              registrationExpiresAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              isFreezed: const fb.BoolReader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              registrationCreatedAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              packageId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18),
              clubId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              memberId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 22),
              staffId: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 24),
              paid: const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [MemberAttendencesData] entity fields to define ObjectBox queries.
class MemberAttendencesData_ {
  /// see [MemberAttendencesData.id]
  static final id =
      QueryIntegerProperty<MemberAttendencesData>(_entities[0].properties[0]);

  /// see [MemberAttendencesData.attendenceId]
  static final attendenceId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[1]);

  /// see [MemberAttendencesData.clubId]
  static final clubId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[2]);

  /// see [MemberAttendencesData.registrationId]
  static final registrationId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[3]);

  /// see [MemberAttendencesData.packageId]
  static final packageId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[4]);

  /// see [MemberAttendencesData.staffId]
  static final staffId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[5]);

  /// see [MemberAttendencesData.memberId]
  static final memberId =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[6]);

  /// see [MemberAttendencesData.createdAt]
  static final createdAt =
      QueryStringProperty<MemberAttendencesData>(_entities[0].properties[7]);
}

/// [MemberData] entity fields to define ObjectBox queries.
class MemberData_ {
  /// see [MemberData.id]
  static final id =
      QueryIntegerProperty<MemberData>(_entities[1].properties[0]);

  /// see [MemberData.memberId]
  static final memberId =
      QueryStringProperty<MemberData>(_entities[1].properties[1]);

  /// see [MemberData.clubId]
  static final clubId =
      QueryStringProperty<MemberData>(_entities[1].properties[2]);

  /// see [MemberData.memberName]
  static final memberName =
      QueryStringProperty<MemberData>(_entities[1].properties[3]);

  /// see [MemberData.memberEmail]
  static final memberEmail =
      QueryStringProperty<MemberData>(_entities[1].properties[4]);

  /// see [MemberData.memberPhone]
  static final memberPhone =
      QueryStringProperty<MemberData>(_entities[1].properties[5]);

  /// see [MemberData.countryCode]
  static final countryCode =
      QueryStringProperty<MemberData>(_entities[1].properties[6]);

  /// see [MemberData.gender]
  static final gender =
      QueryStringProperty<MemberData>(_entities[1].properties[7]);

  /// see [MemberData.staffId]
  static final staffId =
      QueryStringProperty<MemberData>(_entities[1].properties[8]);

  /// see [MemberData.birthYear]
  static final birthYear =
      QueryStringProperty<MemberData>(_entities[1].properties[9]);

  /// see [MemberData.membership]
  static final membership =
      QueryIntegerProperty<MemberData>(_entities[1].properties[10]);

  /// see [MemberData.qrCodeURL]
  static final qrCodeURL =
      QueryStringProperty<MemberData>(_entities[1].properties[11]);

  /// see [MemberData.qrCodeUUID]
  static final qrCodeUUID =
      QueryStringProperty<MemberData>(_entities[1].properties[12]);

  /// see [MemberData.canAuthenticate]
  static final canAuthenticate =
      QueryBooleanProperty<MemberData>(_entities[1].properties[13]);

  /// see [MemberData.isBlocked]
  static final isBlocked =
      QueryBooleanProperty<MemberData>(_entities[1].properties[14]);

  /// see [MemberData.createdAt]
  static final createdAt =
      QueryStringProperty<MemberData>(_entities[1].properties[15]);
}

/// [PlanData] entity fields to define ObjectBox queries.
class PlanData_ {
  /// see [PlanData.id]
  static final id = QueryIntegerProperty<PlanData>(_entities[2].properties[0]);

  /// see [PlanData.planId]
  static final planId =
      QueryStringProperty<PlanData>(_entities[2].properties[1]);

  /// see [PlanData.planClubId]
  static final planClubId =
      QueryStringProperty<PlanData>(_entities[2].properties[2]);

  /// see [PlanData.planTitle]
  static final planTitle =
      QueryStringProperty<PlanData>(_entities[2].properties[3]);

  /// see [PlanData.planAttendance]
  static final planAttendance =
      QueryIntegerProperty<PlanData>(_entities[2].properties[4]);

  /// see [PlanData.planExpiresIn]
  static final planExpiresIn =
      QueryStringProperty<PlanData>(_entities[2].properties[5]);

  /// see [PlanData.isOpen]
  static final isOpen =
      QueryBooleanProperty<PlanData>(_entities[2].properties[6]);

  /// see [PlanData.createdAt]
  static final createdAt =
      QueryStringProperty<PlanData>(_entities[2].properties[7]);
}

/// [Registrations] entity fields to define ObjectBox queries.
class Registrations_ {
  /// see [Registrations.id]
  static final id =
      QueryIntegerProperty<Registrations>(_entities[3].properties[0]);

  /// see [Registrations.registrationId]
  static final registrationId =
      QueryStringProperty<Registrations>(_entities[3].properties[1]);

  /// see [Registrations.registrationIsActive]
  static final registrationIsActive =
      QueryBooleanProperty<Registrations>(_entities[3].properties[2]);

  /// see [Registrations.registrationAttended]
  static final registrationAttended =
      QueryIntegerProperty<Registrations>(_entities[3].properties[3]);

  /// see [Registrations.registrationExpiresAt]
  static final registrationExpiresAt =
      QueryStringProperty<Registrations>(_entities[3].properties[4]);

  /// see [Registrations.isFreezed]
  static final isFreezed =
      QueryBooleanProperty<Registrations>(_entities[3].properties[5]);

  /// see [Registrations.registrationCreatedAt]
  static final registrationCreatedAt =
      QueryStringProperty<Registrations>(_entities[3].properties[6]);

  /// see [Registrations.packageId]
  static final packageId =
      QueryStringProperty<Registrations>(_entities[3].properties[7]);

  /// see [Registrations.clubId]
  static final clubId =
      QueryStringProperty<Registrations>(_entities[3].properties[8]);

  /// see [Registrations.memberId]
  static final memberId =
      QueryStringProperty<Registrations>(_entities[3].properties[9]);

  /// see [Registrations.staffId]
  static final staffId =
      QueryStringProperty<Registrations>(_entities[3].properties[10]);

  /// see [Registrations.paid]
  static final paid =
      QueryIntegerProperty<Registrations>(_entities[3].properties[11]);
}
